### ISSUE TITLE
Whiskeys Page - Get All

### ISSUE THREAD

**Issue by aclai4067** [Kimberly-Hart/East-Barley#64]
# User Story
* As a user, when I navigate to the whiskey route I should see a list of all of the whiskeys that are available.

# AC
**WHEN** the user navigates to the whiskey route
**THEN** they should see a list of all of the whiskeys that are available
**AND** those whiskeys should be listed on a card from (**UPDATE WHEN WE DECIDE ON UI CHOICE**)

# Dev Notes
- [x] First thing that needs to be done is to create a data file for whiskeys in ```src/helpers/data/```
- [x] Inside of the data folder, create a file called whiskeysData.js.
- [x] Inside of whiskeysData.js, write a getAllWhiskeys function like below
```
import axios from 'axios';
// import { baseUrl } from '../apiKeys.json';

const getAllWhiskeys = () => new Promise((resolve, reject) => {
  axios.get('https://localhost:44319/api/products/whiskeys/all')
    .then((result) => resolve(result.data))
    .catch((error) => reject(error));
});

export default { getAllWhiskeys };

```

- [ ] Once you agree on apiKeys setup, replace the localhost with the commented out baseUrl
- [x] Inside the ```components/pages``` folder, create a folder called AllWhiskeys
- [x] inside ```src/components/pages/AllWhiskeys/```, created two files: AllWhiskeys.js and AllWhiskeys.scss.
- [x] inside AllWhiskeys.js, create a class function to render our data, and import both AllWhiskeys.scss and whiskeys data like so:

```
import React from 'react';
import SingleWhiskey from '../../shared/SingleWhiskey/SingleWhiskey';
import whiskeysData from '../../../helpers/data/whiskeysData';
import './AllWhiskeys.scss';

class AllWhiskeys extends React.Component {
    state = {
      whiskeys: [],
    }

    componentDidMount() {
      whiskeysData.getAllWhiskeys()
        .then((whiskeys) => {
          this.setState({ whiskeys });
        })
        .catch((errorFromGetWhiskeys) => console.error({ errorFromGetWhiskeys }));
    }

    render() {
      const { whiskeys } = this.state;
      return (
        <div className="AllWhiskeys">
        { whiskeys.map((whiskey) => <SingleWhiskey key={whiskey.productId} whiskey={whiskey} />)}
        </div>
      );
    }
}

export default AllWhiskeys;

```

- [x] Inside ```components/shared```, make a folder called SingleWhiskey
- [x] Inside the SingleWhiskey folder, create these files: SingleWhiskey.js and SingleWhiskey.scss
- [ ] Inside of SingleWhiskey.js create a class that will will hold the card data from (**UPDATE WHEN WE DECIDE ON UI CHOICE**). File should look as follows:
```
import React, { Component } from 'react';
import whiskeysShape from '../../../helpers/propz/productsShape';
import './SingleWhiskey.scss';

class SingleWhiskey extends Component {
    static propTypes = {
      whiskey: whiskeysShape.whiskeysShape,
    }

    render() {
      const { whiskey } = this.props;
      return (
        <div className="SingleWhiskey">
            <ul>
                <li>Category: {whiskey.category}</li>
                <li>Price: {whiskey.price}</li>
                <li>Title: {whiskey.title}</li>
                <li>Description: {whiskey.description}</li>
                <li>Quantity: {whiskey.quantity}</li>
            </ul>
        </div>
      );
    }
}

export default SingleWhiskey;

```
- [x] Test and make sure the available whiskeys are showing up.

**Comment by phillipsja97** [comment]
![image](https://user-images.githubusercontent.com/51938283/84722855-f8ced780-af49-11ea-9656-fad62a4af853.png)

**Comment by gseals** [comment]
Semantic UI
