### ISSUE TITLE
Beers Page - Get All

### ISSUE THREAD

**Issue by aclai4067** [Kimberly-Hart/East-Barley#65]
# User Story
* As a user, when I navigate to the beer route I should see a list of all of the beer that are available.

# AC
**WHEN** the user navigates to the beer route
**THEN** they should see a list of all of the beer that are available
**AND** those beer should be listed on a card from (**UPDATE WHEN WE DECIDE ON UI CHOICE**)

# Dev Notes
- [x] First thing that needs to be done is to create a data file for beer in ```src/helpers/data/```
- [x] Inside of the data folder, create a file called beersData.js.
- [x] Inside of beersData.js, write a getAllBeers function like below
```
import axios from 'axios';
// import { baseUrl } from '../apiKeys.json';

const getAllBeers = () => new Promise((resolve, reject) => {
  axios.get('https://localhost:44319/api/products/beer/all')
    .then((result) => resolve(result.data))
    .catch((error) => reject(error));
});

export default { getAllBeers };

```

- [ ] Once you agree on apiKeys setup, replace the localhost with the commented out baseUrl
- [x] Inside the ```components/pages``` folder, create a folder called AllBeers
- [x] inside ```src/components/pages/AllBeers/```, created two files: AllBeers.js and AllBeers.scss.
- [x] inside AllBeers.js, create a class function to render our data, and import both AllBeers.scss and beer data like so:

```
import React from 'react';
import SingleBeer from '../../shared/SingleBeer/SingleBeer';
import beersData from '../../../helpers/data/beersData';
import './AllBeers.scss';

class AllBeers extends React.Component {
    state = {
      beers: [],
    }

    componentDidMount() {
      beersData.getAllBeers()
        .then((beers) => {
          this.setState({ beers });
        })
        .catch((errorFromGetBeers) => console.error({ errorFromGetBeers }));
    }

    render() {
      const { beers } = this.state;
      return (
        <div className="AllBeers">
        { beers.map((beer) => <SingleBeer key={beer.productId} beer={beer} />)}
        </div>
      );
    }
}

export default AllBeers;

```

- [x] Inside of ```src/helpers/propz/```, modify the productsShape.js as follows:
```
import PropTypes from 'prop-types';

const productsShape = PropTypes.shape({
  productId: PropTypes.number,
  productTypesTableId: PropTypes.number,
  category: PropTypes.string.isRequired,
  price: PropTypes.number.isRequired,
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  quantity: PropTypes.number.isRequired,
});

export default { productsShape };

```
- [x] Inside ```components/shared```, make a folder called SingleBeer
- [x] Inside the SingleBeer folder, create these files: SingleBeer.js and SingleBeer.scss
- [ ] Inside of SingleBeer.js create a class that will will hold the card data from (**UPDATE WHEN WE DECIDE ON UI CHOICE**). File should look as follows:
```
import React, { Component } from 'react';
import beersShape from '../../../helpers/propz/productsShape';
import './SingleBeer.scss';

class SingleBeer extends Component {
    static propTypes = {
      beer: beersShape.beersShape,
    }

    render() {
      const { beer } = this.props;
      return (
        <div className="SingleBeer">
            <ul>
                <li>Category: {beer.category}</li>
                <li>Price: {beer.price}</li>
                <li>Title: {beer.title}</li>
                <li>Description: {beer.description}</li>
                <li>Quantity: {beer.quantity}</li>
            </ul>
        </div>
      );
    }
}

export default SingleBeer;


```
- [x] Test and make sure the available beer are showing up.

**Comment by phillipsja97** [comment]
![image](https://user-images.githubusercontent.com/51938283/84722912-0e440180-af4a-11ea-9b27-46862ae06910.png)

**Comment by gseals** [comment]
Semantic UI
