### ISSUE TITLE
Books Page - Get All

### ISSUE THREAD

**Issue by aclai4067** [Kimberly-Hart/East-Barley#66]
# User Story
* As a user, when I navigate to the books route I should see a list of all of the books that are available.

# AC
**WHEN** the user navigates to the books route
**THEN** they should see a list of all of the books that are available
**AND** those books should be listed on a card from (**UPDATE WHEN WE DECIDE ON UI CHOICE**)

# Dev Notes
- [x] First thing that needs to be done is to create a data file for books in ```src/helpers/data/```
- [x] Inside of the data folder, create a file called booksData.js.
- [x] Inside of booksData.js, write a getAllbooks function like below
```
import axios from 'axios';
// import { baseUrl } from '../apiKeys.json';

const getAllBooks = () => new Promise((resolve, reject) => {
  axios.get('https://localhost:44319/api/products/books/all')
    .then((result) => resolve(result.data))
    .catch((error) => reject(error));
});

export default { getAllBooks };

```

- [ ] Once you agree on apiKeys setup, replace the localhost with the commented out baseUrl
- [x] Inside the ```components/pages``` folder, create a folder called AllBooks
- [x] inside ```src/components/pages/AllBooks/```, created two files: AllBooks.js and AllBooks.scss.
- [x] inside AllBooks.js, create a class function to render our data, and import both AllBooks.scss and books data like so:

```
import React from 'react';
import SingleBook from '../../shared/SingleBook/SingleBook';
import booksData from '../../../helpers/data/booksData';
import './AllBooks.scss';

class AllBooks extends React.Component {
    state = {
      books: [],
    }

    componentDidMount() {
      booksData.getAllBooks()
        .then((books) => {
          this.setState({ books });
        })
        .catch((errorFromGetBooks) => console.error({ errorFromGetBooks }));
    }

    render() {
      const { books } = this.state;
      return (
        <div className="AllBooks">
        { books.map((book) => <SingleBook key={book.productId} book={book} />)}
        </div>
      );
    }
}

export default AllBooks;

```

- [x] Inside of ```src/helpers/propz/```, create booksShape.js and fill it as follows:
```
import PropTypes from 'prop-types';

const booksShape = PropTypes.shape({
  productId: PropTypes.number,
  productTypesTableId: PropTypes.number,
  category: PropTypes.string.isRequired,
  price: PropTypes.number.isRequired,
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  quantity: PropTypes.number.isRequired,
  bookDetailsId: PropTypes.number,
  author: PropTypes.string.isRequired,
  isbn: PropTypes.string.isRequired,
  publisher: PropTypes.string.isRequired,
  pageCount: PropTypes.number.isRequired,
});

export default { booksShape };

```
- [x] Inside ```components/shared```, make a folder called SingleBook
- [x] Inside the SingleBook folder, create these files: SingleBook.js and SingleBook.scss
- [ ] Inside of SingleBook.js create a class that will will hold the card data from (**UPDATE WHEN WE DECIDE ON UI CHOICE**). File should look as follows:
```
import React, { Component } from 'react';
import booksShape from '../../../helpers/propz/booksShape';
import './SingleBook.scss';

class SingleBook extends Component {
    static propTypes = {
      book: booksShape.booksShape,
    }

    render() {
      const { book } = this.props;
      return (
        <div className="SingleBook">
            <ul>
                <li>Category: {book.category}</li>
                <li>Price: {book.price}</li>
                <li>Title: {book.title}</li>
                <li>Description: {book.description}</li>
                <li>Quantity: {book.quantity}</li>
                <li>Author: {book.author}</li>
                <li>ISBN: {book.isbn}</li>
                <li>Publisher: {book.publisher}</li>
                <li>Page Count: {book.pageCount}</li>
            </ul>
        </div>
      );
    }
}

export default SingleBook;

```
- [x] Test and make sure the available books are showing up.

**Comment by phillipsja97** [comment]
![image](https://user-images.githubusercontent.com/51938283/84722886-05ebc680-af4a-11ea-970d-9a8f9b8963dc.png)

**Comment by gseals** [comment]
Semantic UI
